FROM arm32v6/node:17-alpine3.12

WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig*.json ./

RUN npm install
COPY . .
RUN npm run build

FROM arm32v6/node:17-alpine3.12

WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig*.json ./

RUN npm install --only=production

COPY --from=0 /usr/src/app/build .
COPY --from=0 /usr/src/app/.env .

RUN npm install pm2 -g
ENV NODE_ENV=prod

CMD ["pm2-runtime","bot.js"]